### ISSUE TITLE
Put text memory on canvas

### ISSUE THREAD

**Issue by Skylarius** [Skylarius/GGJ2021#20]
![image](https://user-images.githubusercontent.com/27561860/107580778-61647600-6bf7-11eb-88c6-f39cb0593c31.png)
This bug is due to the presence of the text as an object in the 3d scene and not as an element in the canvas.

**Comment by Skylarius** [comment]
Fixed!
![image](https://user-images.githubusercontent.com/27561860/107892812-d69db700-6f27-11eb-92b9-316de8b5739e.png)

**Comment by JacopoFabrini** [comment]
Grande!!
