### ISSUE TITLE
Superwall not working properly

### ISSUE THREAD

**Issue by JacopoFabrini** [Skylarius/GGJ2021#23]
The superwall collider used to block the player from exiting the scene is not working properly.
In fact, when the player jump towards it while pushing/facing another collider (a wall of the room for example) he's able to pass through it.

**Comment by Skylarius** [comment]
This is caused by the fucking unity phisics. I'm trying several solutions but it's still not working. :) I'm on it btw

**Comment by Skylarius** [comment]
Progressing on this, still need to stop player movement when against objects but now it will not go through the wall
