### ISSUE TITLE
Walking animation doesn't seem fluid anymore

### ISSUE THREAD

**Issue by JacopoFabrini** [Skylarius/GGJ2021#29]
It seems to me that when the main character is moving the animation is not as fluid as it was before.

(Question by J: Is it possible that the animation is restarting itself continuosly while moving?)

**Comment by Skylarius** [comment]
1) The animation is not anymore fluid because I changed some parameters to fix the superwall task (https://github.com/Skylarius/GGJ2021/issues/23).
2) Yes, the animation is restarting himself. Will fix it

**Comment by Skylarius** [comment]
![image](https://user-images.githubusercontent.com/27561860/108632700-916e0d80-7470-11eb-82b2-20eb883681c4.png)
After summoning the devil the animation is OK again
